/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<number, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AbsenceBlackout {
  created_at: Generated<Timestamp | null>;
  created_by_user_id: number;
  department_id: number | null;
  from_date: string;
  hotel_id: number;
  id: Generated<number>;
  max_concurrent_absent: number | null;
  reason: string | null;
  to_date: string;
}

export interface AbsenceType {
  code: string;
  counts_against_allowance: Generated<boolean>;
  credits_hours: Generated<boolean>;
  name: string;
  primary_menu: Generated<boolean>;
  reduces_target: Generated<boolean>;
  requires_certificate: Generated<boolean>;
  salary_only: Generated<boolean>;
}

export interface Admin {
  admin_id: Generated<number>;
  created_at: Generated<Timestamp | null>;
  created_by_id: number;
  first_name: string;
  last_name: string;
  revoked_at: Timestamp | null;
  updated_at: Generated<Timestamp | null>;
  user_id: number;
}

export interface AdminCompany {
  admin_id: number;
  assigned_at: Generated<Timestamp | null>;
  assigned_by_id: number;
  company_id: number;
}

export interface AdminHotel {
  admin_id: number;
  assigned_at: Generated<Timestamp | null>;
  assigned_by_id: number;
  hotel_id: number;
}

export interface Announcement {
  body: string;
  company_id: number;
  created_at: Generated<Timestamp | null>;
  created_by_user_id: number;
  hotel_id: number | null;
  id: Generated<number>;
  pinned: Generated<boolean>;
  publish_at: Generated<Timestamp>;
  requires_ack: Generated<boolean>;
  title: string;
}

export interface AnnouncementAck {
  acknowledged_at: Generated<Timestamp>;
  announcement_id: number;
  employee_id: number;
}

export interface ApiKey {
  allowed_cidrs: string[] | null;
  company_id: number;
  created_at: Generated<Timestamp>;
  created_by_user_id: number | null;
  expires_at: Timestamp;
  hotel_id: number | null;
  id: Generated<number>;
  key_hash: string;
  key_prefix: string;
  last_used_at: Timestamp | null;
  last_used_ip: string | null;
  name: string;
  revoked_at: Timestamp | null;
  scopes: Generated<string[]>;
}

export interface ArbeitszeitkontoEntry {
  created_at: Generated<Timestamp | null>;
  created_by_user_id: number;
  employee_id: number;
  entry_date: string;
  entry_type: string;
  hours: Numeric;
  id: Generated<number>;
  note: string;
}

export interface AuditLog {
  action: string;
  actor_id: number | null;
  actor_type: string | null;
  chain_key: Generated<number>;
  company_id: number | null;
  created_at: Generated<Timestamp | null>;
  entity_id: number | null;
  entity_type: string | null;
  entry_hash: string | null;
  hash_version: Generated<number>;
  hotel_id: number | null;
  id: Generated<Int8>;
  ip_address: string | null;
  new_values: Json | null;
  old_values: Json | null;
  prev_hash: string | null;
  reason: string | null;
  status: string | null;
  user_agent: string | null;
}

export interface CalendarFeed {
  created_at: Generated<Timestamp | null>;
  employee_id: number;
  id: Generated<number>;
  revoked_at: Timestamp | null;
  token_hash: string;
}

export interface Company {
  created_at: Generated<Timestamp | null>;
  created_by_id: number;
  grace_period_minutes: Generated<number>;
  id: Generated<number>;
  managers_can_see_phone: Generated<boolean>;
  name: string;
  pin_length: Generated<number>;
  retention_months: Generated<number>;
  rule_profile_id: number | null;
  schedule_change_notice_days: Generated<number>;
  sick_backdate_days: Generated<number>;
  swap_approval: Generated<string>;
  team_absence_visibility: Generated<string>;
}

export interface CompanyFeature {
  company_id: number;
  enabled: boolean;
  feature: string;
  updated_at: Generated<Timestamp | null>;
  updated_by_user_id: number | null;
}

export interface Department {
  color: string | null;
  created_at: Generated<Timestamp | null>;
  hotel_id: number;
  id: Generated<number>;
  max_concurrent_absent: number | null;
  name: string;
}

export interface Employee {
  anonymised_at: Timestamp | null;
  badge_hash: string | null;
  company_id: number;
  contact_email: string | null;
  contract_end_date: string | null;
  contract_start_date: string;
  created_at: Generated<Timestamp | null>;
  created_by_id: number | null;
  date_of_birth: string;
  display_name: Generated<string | null>;
  employee_id: Generated<number>;
  first_name: string;
  is_floater: Generated<boolean>;
  last_name: string;
  opening_balance_hours: Generated<Numeric>;
  personnel_number: string;
  phone: string | null;
  pin_failed_count: Generated<number>;
  pin_hash: string;
  pin_locked_until: Timestamp | null;
  pin_set_at: Generated<Timestamp>;
  preferred_language: Generated<string>;
  primary_department_id: number;
  primary_hotel_id: number;
  status: Generated<string>;
  terminated_at: Timestamp | null;
  termination_reason: string | null;
  updated_at: Generated<Timestamp | null>;
  user_id: number;
  work_time_protection: Generated<string>;
}

export interface EmployeeAvailability {
  employee_id: number;
  from_time: string;
  id: Generated<number>;
  kind: string;
  note: string | null;
  to_time: string;
  valid_from: Generated<string>;
  valid_to: string | null;
  weekday: number;
}

export interface EmployeeContract {
  account_max_hours: Numeric | null;
  account_min_hours: Numeric | null;
  carryover_limit_days: Generated<Numeric>;
  created_at: Generated<Timestamp | null>;
  created_by_id: number | null;
  daily_target_hours: Numeric | null;
  employee_id: number;
  employment_type: string;
  gets_public_holiday: Generated<boolean>;
  id: Generated<number>;
  monthly_hours_cap: Numeric | null;
  rest_vacation_days_per_year: Numeric | null;
  target_hours_per_month: Numeric | null;
  target_hours_per_week: Numeric | null;
  vacation_days_per_year: Numeric;
  valid_from: string;
  valid_to: string | null;
  work_days_per_week: number;
  working_model: string;
  working_weekdays: Generated<number[]>;
}

export interface EmployeeDepartment {
  department_id: number;
  employee_id: number;
}

export interface EmployeeDocument {
  content_enc: Buffer;
  created_at: Generated<Timestamp | null>;
  doc_type: string;
  employee_id: number;
  file_name: string;
  file_ref: Generated<string>;
  id: Generated<number>;
  mime: string;
  size_bytes: number;
  title: string;
  uploaded_by_user_id: number;
  valid_until: string | null;
  visible_to_employee: Generated<boolean>;
}

export interface EmployeeHotel {
  employee_id: number;
  hotel_id: number;
}

export interface EmployeeLeaveWish {
  created_at: Generated<Timestamp | null>;
  decided_at: Timestamp | null;
  decided_by_user_id: number | null;
  decision_note: string | null;
  employee_id: number;
  end_date: string;
  hotel_id: number;
  id: Generated<number>;
  leave_days: Numeric;
  priority: number;
  reason: string | null;
  requested_at: Generated<Timestamp | null>;
  start_date: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp | null>;
}

export interface EmployeeQualification {
  employee_id: number;
  qualification_id: number;
  valid_until: string | null;
}

export interface EmployeeShiftWish {
  created_at: Generated<Timestamp | null>;
  date: string;
  decided_at: Timestamp | null;
  decided_by_user_id: number | null;
  decision_note: string | null;
  employee_id: number;
  hotel_id: number;
  id: Generated<number>;
  priority: number;
  reason: string | null;
  requested_at: Generated<Timestamp | null>;
  shift_id: number;
  status: Generated<string>;
  updated_at: Generated<Timestamp | null>;
}

export interface EmployeeVacationAllowance {
  allocated_days: Numeric;
  carried_contractual_days: Generated<Numeric>;
  carried_statutory_days: Generated<Numeric>;
  carryover_expires_on: string | null;
  contractual_days: Numeric;
  created_at: Generated<Timestamp | null>;
  employee_id: number;
  id: Generated<number>;
  statutory_days: Numeric;
  updated_at: Generated<Timestamp | null>;
  used_days: Generated<Numeric>;
  vacation_days_total: Numeric;
  year: number;
}

export interface FeedComment {
  author_name: string;
  author_user_id: number;
  body: string;
  created_at: Generated<Timestamp | null>;
  deleted_at: Timestamp | null;
  id: Generated<number>;
  post_id: number;
}

export interface FeedLike {
  post_id: number;
  user_id: number;
}

export interface FeedPost {
  author_name: string;
  author_user_id: number;
  body: string;
  created_at: Generated<Timestamp | null>;
  deleted_at: Timestamp | null;
  hotel_id: number;
  id: Generated<number>;
}

export interface Hotel {
  allow_web_punch: Generated<boolean>;
  break_mode: Generated<string>;
  city: string | null;
  company_id: number;
  created_at: Generated<Timestamp | null>;
  deactivated_at: Timestamp | null;
  employee_hours_visibility: Generated<string>;
  federal_state: string | null;
  id: Generated<number>;
  is_active: Generated<boolean>;
  kiosk_identification: Generated<string>;
  name: string;
  rule_profile_id: number | null;
  timezone: Generated<string>;
  web_punch_allowed_cidrs: string[] | null;
}

export interface HourCategory {
  active: Generated<boolean>;
  code: string;
  company_id: number | null;
  id: Generated<number>;
  name: string;
  rule: Json;
}

export interface ImportJob {
  admin_id: number | null;
  created_at: Generated<Timestamp | null>;
  created_by_user_id: number | null;
  created_count: number | null;
  credentials_downloaded_at: Timestamp | null;
  credentials_enc: Buffer | null;
  credentials_expires_at: Timestamp | null;
  dry_run: Generated<boolean>;
  error_count: number | null;
  file_name: string | null;
  finished_at: Timestamp | null;
  id: Generated<number>;
  import_type: Generated<string>;
  on_duplicate_email: Generated<string>;
  raw_rows: Json | null;
  result: Json | null;
  skipped_count: number | null;
  status: Generated<string>;
  total_rows: number | null;
  updated_count: number | null;
}

export interface KioskDevice {
  created_at: Generated<Timestamp | null>;
  hotel_id: number;
  id: Generated<number>;
  last_seen_at: Timestamp | null;
  name: string;
  registered_by_user_id: number;
  status: Generated<string>;
  token_hash: string;
}

export interface ManagementQuestion {
  answer: string | null;
  answered_at: Timestamp | null;
  answered_by_user_id: number | null;
  body: string;
  created_at: Generated<Timestamp | null>;
  employee_id: number;
  hotel_id: number;
  id: Generated<number>;
  status: Generated<string>;
  subject: string;
}

export interface Manager {
  created_at: Generated<Timestamp | null>;
  created_by_id: number | null;
  first_name: string;
  last_name: string;
  manager_id: Generated<number>;
  revoked_at: Timestamp | null;
  updated_at: Generated<Timestamp | null>;
  user_id: number;
}

export interface ManagerHotel {
  hotel_id: number;
  manager_id: number;
}

export interface Notification {
  created_at: Generated<Timestamp | null>;
  employee_id: number | null;
  id: Generated<number>;
  kind: string;
  payload: Json | null;
  read_at: Timestamp | null;
  user_id: number;
}

export interface OccupancyForecast {
  created_at: Generated<Timestamp>;
  hotel_id: number;
  id: Generated<number>;
  occupancy_pct: number;
  on_date: string;
}

export interface OfflinePunchLog {
  client_id: string;
  created_at: Generated<Timestamp>;
  detail: string | null;
  id: Generated<number>;
  kiosk_device_id: number;
  outcome: string;
  punch_record_id: number | null;
}

export interface OpenShift {
  created_at: Generated<Timestamp | null>;
  created_by_role: string;
  created_by_user_id: number;
  department_id: number;
  filled_schedule_id: number | null;
  hotel_id: number;
  id: Generated<number>;
  planned_break_minutes: Generated<number>;
  planned_end: Timestamp;
  planned_start: Timestamp;
  shift_date: string;
  shift_id: number | null;
  status: Generated<string>;
}

export interface OpenShiftClaim {
  created_at: Generated<Timestamp | null>;
  decided_by_user_id: number | null;
  employee_id: number;
  id: Generated<number>;
  open_shift_id: number;
  status: Generated<string>;
}

export interface PayrollPeriod {
  closed_at: Timestamp | null;
  closed_by_user_id: number | null;
  company_id: number;
  hotel_id: number | null;
  id: Generated<number>;
  period_end: string;
  period_start: string;
  reopen_reason: string | null;
  reopened_by_user_id: number | null;
  status: Generated<string>;
}

export interface PublicHoliday {
  company_id: number | null;
  created_at: Generated<Timestamp | null>;
  date: string;
  federal_state: string | null;
  hotel_id: number | null;
  id: Generated<number>;
  is_holiday: Generated<boolean>;
  name: string;
  scope: string;
}

export interface PunchRecord {
  actual_break_minutes: number | null;
  actual_punch_in: Timestamp;
  actual_punch_out: Timestamp | null;
  approval_notes: string | null;
  approval_source: string | null;
  approval_status: Generated<string>;
  approved_at: Timestamp | null;
  approved_by_role: string | null;
  approved_by_user_id: number | null;
  auto_checked_out: Generated<boolean>;
  break_segments: Json | null;
  created_at: Generated<Timestamp | null>;
  created_by_user_id: number | null;
  employee_id: number;
  end_variation_minutes: number | null;
  hotel_id: number;
  id: Generated<number>;
  is_unplanned: Generated<boolean>;
  kiosk_device_id: number | null;
  offline_punch: Generated<boolean>;
  paid_end: Timestamp | null;
  paid_hours: Numeric | null;
  paid_start: Timestamp | null;
  planned_end: Timestamp | null;
  planned_start: Timestamp | null;
  required_break_minutes: number | null;
  schedule_id: number | null;
  shift_date: string;
  source: Generated<string>;
  start_variation_minutes: number | null;
  under_break_warning: Generated<boolean>;
  updated_at: Generated<Timestamp | null>;
}

export interface PunchRecordCategoryMinutes {
  category_code: string;
  minutes: number;
  punch_record_id: number;
}

export interface PunchRecordHistory {
  change_type: string;
  changed_by_role: string | null;
  changed_by_user_id: number | null;
  created_at: Generated<Timestamp | null>;
  id: Generated<number>;
  new_values: Json | null;
  old_values: Json | null;
  punch_record_id: number;
  reason: string | null;
}

export interface Qualification {
  company_id: number;
  has_expiry: Generated<boolean>;
  id: Generated<number>;
  name: string;
}

export interface RefreshToken {
  active_employee_id: number | null;
  active_role: string;
  created_at: Generated<Timestamp | null>;
  expires_at: Timestamp;
  id: Generated<Int8>;
  revoked_at: Timestamp | null;
  token_hash: string;
  user_id: number;
}

export interface RuleProfile {
  company_id: number | null;
  created_at: Generated<Timestamp | null>;
  id: Generated<number>;
  kind: string;
  name: string;
  rules: Json;
  valid_from: Generated<string>;
}

export interface Schedule {
  cancel_reason: string | null;
  created_at: Generated<Timestamp | null>;
  created_by_role: string;
  created_by_user_id: number;
  employee_id: number;
  hotel_id: number;
  id: Generated<number>;
  planned_break_minutes: Generated<number>;
  planned_end: Timestamp;
  planned_start: Timestamp;
  published_at: Timestamp | null;
  shift_date: string;
  shift_id: number | null;
  status: Generated<string>;
  time_off_id: number | null;
  updated_at: Generated<Timestamp | null>;
  version: Generated<number>;
}

export interface ScheduleSnapshot {
  hotel_id: number;
  id: Generated<number>;
  published_at: Generated<Timestamp>;
  published_by_user_id: number;
  snapshot: Json;
  week_start: string;
}

export interface SchemaMigrations {
  applied_at: Generated<Timestamp>;
  name: string;
}

export interface Shift {
  break_duration_minutes: Generated<number>;
  created_at: Generated<Timestamp | null>;
  department_id: number;
  end_time: string;
  hotel_id: number;
  id: Generated<number>;
  name: string;
  required_qualification_id: number | null;
  start_time: string;
}

export interface ShiftStaffingRequirement {
  id: Generated<number>;
  on_date: string | null;
  required_headcount: number;
  shift_id: number;
  weekday: number | null;
}

export interface ShiftSwapRequest {
  counterpart_employee_id: number | null;
  counterpart_schedule_id: number | null;
  created_at: Generated<Timestamp | null>;
  decided_at: Timestamp | null;
  decided_by_role: string | null;
  decided_by_user_id: number | null;
  decision_note: string | null;
  expires_at: Timestamp;
  hotel_id: number;
  id: Generated<number>;
  reason: string | null;
  requester_employee_id: number;
  schedule_id: number;
  status: Generated<string>;
}

export interface SsoIdentity {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  provider_id: number;
  subject: string;
  user_id: number;
}

export interface SsoProvider {
  client_id: string;
  client_secret_enc: Buffer;
  company_id: number;
  created_at: Generated<Timestamp>;
  enabled: Generated<boolean>;
  id: Generated<number>;
  issuer: string;
}

export interface SsoTicketUse {
  jti: string;
  used_at: Generated<Timestamp>;
}

export interface StaffingRule {
  created_at: Generated<Timestamp>;
  headcount: number;
  hotel_id: number;
  id: Generated<number>;
  min_occupancy_pct: number;
  shift_id: number;
}

export interface SuperAdmin {
  created_at: Generated<Timestamp | null>;
  first_name: string;
  last_name: string;
  revoked_at: Timestamp | null;
  super_admin_id: Generated<number>;
  updated_at: Generated<Timestamp | null>;
  user_id: number;
}

export interface TimeCorrectionRequest {
  correction_type: string;
  created_at: Generated<Timestamp | null>;
  decided_at: Timestamp | null;
  decided_by_role: string | null;
  decided_by_user_id: number | null;
  decision_notes: string | null;
  employee_id: number;
  hotel_id: number;
  id: Generated<number>;
  punch_record_id: number | null;
  reason: string;
  requested_break_minutes: number | null;
  requested_in: Timestamp | null;
  requested_out: Timestamp | null;
  status: Generated<string>;
}

export interface TimeOff {
  backdate_override_reason: string | null;
  certificate_status: string | null;
  counts_against_allowance: boolean;
  created_at: Generated<Timestamp | null>;
  created_by_user_id: number;
  credits_hours: Generated<boolean>;
  decided_at: Timestamp | null;
  decided_by_user_id: number | null;
  decision_note: string | null;
  employee_id: number;
  end_date: string;
  half_day: string | null;
  id: Generated<number>;
  reason: string | null;
  start_date: string;
  status: Generated<string>;
  time_off_days: Numeric;
  type: string;
  updated_at: Generated<Timestamp | null>;
}

export interface TimeVariation {
  actual_time: Timestamp;
  created_at: Generated<Timestamp | null>;
  employee_id: number;
  hotel_id: number;
  id: Generated<number>;
  planned_time: Timestamp | null;
  punch_record_id: number;
  reason: string | null;
  review_notes: string | null;
  reviewed_at: Timestamp | null;
  reviewed_by_role: string | null;
  reviewed_by_user_id: number | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp | null>;
  variation_minutes: number | null;
  variation_type: string;
}

export interface UserAccount {
  created_at: Generated<Timestamp | null>;
  email: string | null;
  failed_login_count: Generated<number>;
  id: Generated<number>;
  invitation_expires_at: Timestamp | null;
  invitation_token_hash: string | null;
  last_login_at: Timestamp | null;
  locked_until: Timestamp | null;
  password_hash: string | null;
  status: Generated<string>;
  totp_enabled: Generated<boolean>;
  totp_secret_enc: Buffer | null;
  updated_at: Generated<Timestamp | null>;
  username: string | null;
}

export interface VacationNotice {
  acknowledged_at: Timestamp | null;
  channel: string;
  employee_id: number;
  id: Generated<number>;
  kind: string;
  remaining_days: Numeric;
  sent_at: Generated<Timestamp>;
  year: number;
}

export interface WebauthnCredential {
  counter: Generated<Int8>;
  created_at: Generated<Timestamp>;
  credential_id: string;
  id: Generated<number>;
  last_used_at: Timestamp | null;
  name: string;
  public_key: Buffer;
  transports: string[] | null;
  user_id: number;
}

export interface DB {
  absence_blackout: AbsenceBlackout;
  absence_type: AbsenceType;
  admin: Admin;
  admin_company: AdminCompany;
  admin_hotel: AdminHotel;
  announcement: Announcement;
  announcement_ack: AnnouncementAck;
  api_key: ApiKey;
  arbeitszeitkonto_entry: ArbeitszeitkontoEntry;
  audit_log: AuditLog;
  calendar_feed: CalendarFeed;
  company: Company;
  company_feature: CompanyFeature;
  department: Department;
  employee: Employee;
  employee_availability: EmployeeAvailability;
  employee_contract: EmployeeContract;
  employee_department: EmployeeDepartment;
  employee_document: EmployeeDocument;
  employee_hotel: EmployeeHotel;
  employee_leave_wish: EmployeeLeaveWish;
  employee_qualification: EmployeeQualification;
  employee_shift_wish: EmployeeShiftWish;
  employee_vacation_allowance: EmployeeVacationAllowance;
  feed_comment: FeedComment;
  feed_like: FeedLike;
  feed_post: FeedPost;
  hotel: Hotel;
  hour_category: HourCategory;
  import_job: ImportJob;
  kiosk_device: KioskDevice;
  management_question: ManagementQuestion;
  manager: Manager;
  manager_hotel: ManagerHotel;
  notification: Notification;
  occupancy_forecast: OccupancyForecast;
  offline_punch_log: OfflinePunchLog;
  open_shift: OpenShift;
  open_shift_claim: OpenShiftClaim;
  payroll_period: PayrollPeriod;
  public_holiday: PublicHoliday;
  punch_record: PunchRecord;
  punch_record_category_minutes: PunchRecordCategoryMinutes;
  punch_record_history: PunchRecordHistory;
  qualification: Qualification;
  refresh_token: RefreshToken;
  rule_profile: RuleProfile;
  schedule: Schedule;
  schedule_snapshot: ScheduleSnapshot;
  schema_migrations: SchemaMigrations;
  shift: Shift;
  shift_staffing_requirement: ShiftStaffingRequirement;
  shift_swap_request: ShiftSwapRequest;
  sso_identity: SsoIdentity;
  sso_provider: SsoProvider;
  sso_ticket_use: SsoTicketUse;
  staffing_rule: StaffingRule;
  super_admin: SuperAdmin;
  time_correction_request: TimeCorrectionRequest;
  time_off: TimeOff;
  time_variation: TimeVariation;
  user_account: UserAccount;
  vacation_notice: VacationNotice;
  webauthn_credential: WebauthnCredential;
}
