// Writes the API reference: docs/api/openapi.internal.json, docs/api/openapi.public.json and docs/api/REFERENCE.md.
// Usage: pnpm docs:api   (needs DATABASE_URL like every other script; nothing is written to the database)
import { mkdirSync, writeFileSync } from 'node:fs';
import { ERROR_STATUS } from '@dienst/shared';
import { buildApp } from '../app';

type Op = { summary?: string; description?: string; tags?: string[]; security?: unknown[] };
type Doc = { paths: Record<string, Record<string, Op>> };

const app = await buildApp({ autoCheckout: false });
await app.ready();
const internal = app.swagger() as unknown as Doc;
const pub = (await app.inject({ method: 'GET', url: '/api/public/v1/openapi.json' })).json() as Doc;
await app.close();

const out = new URL('../../../../docs/api/', import.meta.url);
mkdirSync(out, { recursive: true });
const stable = (o: unknown) => JSON.stringify(o, null, 2) + '\n';
writeFileSync(new URL('openapi.internal.json', out), stable(internal));
writeFileSync(new URL('openapi.public.json', out), stable(pub));

const METHODS = ['get', 'post', 'put', 'patch', 'delete'];
const group = (p: string) => p.replace(/^\/api\/(?:public\/)?v1\/?/, '').split('/')[0] || 'root';
const rows = (doc: Doc) => {
  const by = new Map<string, string[]>();
  for (const path of Object.keys(doc.paths).sort()) {
    for (const m of METHODS) {
      const op = doc.paths[path]?.[m];
      if (!op) continue;
      const g = group(path);
      const line = `| \`${m.toUpperCase()}\` | \`${path}\` | ${(op.summary ?? '').replace(/\|/g, '/')} |`;
      by.set(g, [...(by.get(g) ?? []), line]);
    }
  }
  return [...by.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([g, l]) => `### ${g}\n\n| Method | Path | Summary |\n|---|---|---|\n${l.join('\n')}\n`)
    .join('\n');
};
const count = (d: Doc) => Object.values(d.paths).reduce((n, p) => n + METHODS.filter((m) => p[m]).length, 0);

writeFileSync(
  new URL('REFERENCE.md', out),
  `# API reference

Generated by \`pnpm docs:api\` from the route schemas. Do not edit by hand; CI fails when it is out of date.
Machine-readable: [openapi.internal.json](openapi.internal.json) (${count(internal)} operations), [openapi.public.json](openapi.public.json) (${count(pub)} operations).
Live copies: \`GET /api/v1/openapi.json\` (admins) and \`GET /api/public/v1/openapi.json\`.

## Conventions

- Base path \`/api/v1\`; JSON in camelCase; dates \`YYYY-MM-DD\`; timestamps ISO-8601 with offset.
- Authentication: \`Authorization: Bearer <access token>\` from \`POST /api/v1/auth/login\` (+ \`/auth/select-role\`); tablets send \`X-Kiosk-Token\`; the public API takes an API key (see [../PUBLIC-API.md](../PUBLIC-API.md)).
- Errors: \`{ "error": { "code", "message", "details" } }\`. Codes are listed in \`packages/shared/src/errors.ts\`.
- State-changing requests from browsers must come from the configured web origin.
- Every list is scoped to the caller's companies and hotels on the server.

## Error codes\n\n| Code | HTTP status |\n|---|---|\n${Object.entries(ERROR_STATUS).map(([c, st]) => `| \`${c}\` | ${st} |`).join('\n')}\n\n## Public API (read only)

${rows(pub)}
## Internal API

${rows(internal)}`,
);
console.log(`internal ${count(internal)}, public ${count(pub)} operations`);
