/* eslint-disable */
// GENERATED by scripts/types/gen.mjs from live API responses of the demo seed. Do not edit by hand;
// refine shapes with a mapper type in dto.ts, or extend the generator's sample list.

import type {
  Items,
  CompanyDto,
  HotelDto,
  HotelSettingsDto,
  DepartmentDto,
  KioskDeviceDto,
  ShiftDto,
  QualificationDto,
  AvailabilityDto,
  DocumentDto,
  BlackoutDto,
  ShiftWishDto,
  LeaveWishDto,
  TimeOffRequestDto,
  CorrectionDto,
  NotificationDto,
  SwapDto,
  OpenShiftDto,
  StaffingRuleDto,
  PayrollPeriodDto,
  HourCategoryDto,
  ContractDto,
  Paged,
  NamedRef,
  EmployeeViewKind,
  VacationSummaryDto,
  EmployeeSummaryDto,
  EmployeeDetailDto,
  LoginResponseDto,
  SessionDto,
  TwoFactorSetupDto,
  ExitStatementDto,
  ViolationDto,
  MyOpenShiftDto,
  TeamAbsenceItemDto,
  StaffingSuggestionDto,
  ColleagueShiftDto,
  AttendanceHistoryEntryDto,
  LiveLateDto,
  LiveNeedsReviewDto,
  FeedCommentDto,
  RestCompensationRowDto,
  SsoProviderDto,
  HourCategoryRule,
  OpenShiftClaimDto,
  OpenShiftWithClaimsDto,
  PunchHotelDto,
  FeaturesDto,
  WishWho,
  WishListItemDto,
  GridAbsenceDto,
  CandidateDto,
  ValidateResultDto,
  CopyWeekResultDto,
  SlotDto,
} from './dto';

export type MyOpenShiftList = Items<MyOpenShiftDto>;
export type TeamAbsenceDto = { enabled: boolean; items: TeamAbsenceItemDto[] };
export type WishList = Items<WishListItemDto>;
export type StaffingSuggestionList = Items<StaffingSuggestionDto>;
export type RestCompensationList = Items<RestCompensationRowDto>;

/** GET /feed */
export type FeedResponse = {
  items: Array<{
    id: number;
    hotelId: number;
    author: string;
    body: string;
    createdAt: string;
    mine: boolean;
    canDelete: boolean;
    likes: number;
    likedByMe: boolean;
    comments: FeedCommentDto[];
  }>;
};

/** GET /me/time-account */
export type TimeAccountDto = { employeeId: number; asOf: string; balanceHours: number };

/** GET /me/time-account/ledger */
export type LedgerDto = {
  asOf: string;
  balanceHours: number;
  lines: Array<{ month: string; type: string; hours: number; note: string | null; entryId: number | null }>;
};

/** GET /approvals/count */
export type ApprovalCountDto = {
  total: number;
  workedTime: number;
  corrections: number;
  absences: number;
  questions: number;
};

/** GET /employees/1/qualifications */
export type QualificationHeldList = {
  items: Array<{ qualificationId: number; name: string; hasExpiry: boolean; validUntil: string }>;
};

/** GET /employees/1/documents */
export type DocumentList = {
  items: Array<{
    id: number;
    employeeId: number;
    docType: string;
    title: string;
    fileName: string;
    mime: string;
    sizeBytes: number;
    validUntil: string;
    visibleToEmployee: boolean;
    createdAt: string;
  }>;
};

/** GET /vacation/overview */
export type VacationOverviewDto = {
  year: number;
  today: string;
  employees: Array<{
    employeeId: number;
    displayName: string;
    hotelId: number;
    departmentId: number;
    departmentName: string;
    entitlement: number;
    carryover: number;
    carryoverExpiresOn: string | null;
    taken: number;
    planned: number;
    requested: number;
    remaining: number;
    months: Array<number>;
    entries: Array<{
      id: number;
      from: string;
      to: string;
      days: number;
      halfDay: string | null;
      status: string;
    }>;
  }>;
};

/** GET /vacation/notices */
export type VacationNoticeList = {
  items: Array<{
    id: number;
    employeeId: number;
    displayName: string;
    kind: string;
    remainingDays: number;
    channel: string;
    sentAt: string;
    acknowledgedAt: string | null;
  }>;
};

/** GET /users */
export type UserList = {
  items: Array<{
    userId: number;
    name: string;
    login: string;
    roles: Array<{ role: string; hotelNames: Array<string>; companyName?: string }>;
    lastLoginAt: null | string;
    status: string;
  }>;
  page: number;
  pageSize: number;
  total: number;
};

/** GET /admins */
export type AdminList = {
  items: Array<{
    adminId: number;
    firstName: string;
    lastName: string;
    email: string;
    status: string;
    lastLoginAt: string;
    companyIds: Array<number>;
  }>;
};

/** GET /setup/status */
export type SetupStatusDto = {
  companyId: number;
  hotelsDepartments: { done: boolean; count: number };
  employees: { done: boolean; count: number };
  invitations: { done: boolean; count: number };
  tablet: { done: boolean; count: number };
  rules: { done: boolean };
  firstPublish: { done: boolean };
};

/** GET /setup/overview */
export type SetupOverviewDto = {
  companyId: number;
  kpis: {
    employees: number;
    activeUsers: number;
    tabletsOnline: number;
    tabletsTotal: number;
    openRequests: number;
  };
  actionNeeded: Array<{ kind: string; count: number }>;
  recentChanges: Array<{
    id: string;
    at: string;
    actor: string;
    action: string;
    entityType: string;
    entityId: number;
  }>;
};

/** GET /analytics/summary */
export type AnalyticsSummaryDto = {
  from: string;
  to: string;
  departments: Array<{
    departmentId: number;
    name: string;
    hotelId: number;
    hotel: string;
    employees: number;
    plannedHours: number;
    actualHours: number;
    timeAccountHours: number;
    absenceRate: number | null;
  }>;
  approvals: { pending: number; buckets: { '0-2': number; '3-5': number; '6+': number } };
  overrides: number;
  corrections: { requests: number; records: number; rate: number };
  openSlots: number;
};

/** GET /me/announcements */
export type MyAnnouncementList = {
  items: Array<{
    id: number;
    hotelId: number | null;
    title: string;
    body: string;
    pinned: boolean;
    requiresAck: boolean;
    publishAt: string;
    acknowledged: boolean;
  }>;
};

/** GET /me/swap-requests */
export type MySwapList = {
  items: Array<{
    id: number;
    hotelId: number;
    scheduleId: number;
    requesterEmployeeId: number;
    counterpartEmployeeId: number;
    counterpartScheduleId: number | null;
    status: string;
    reason: string;
    decisionNote: string | null;
    expiresAt: string;
    createdAt: string;
    role: string;
    eligible: string | null;
    slot: { id: number; date: string; start: string; end: string; shiftName: string; employeeId: number };
    counterpartSlot: SlotDto | null;
  }>;
};

/** GET /me/questions */
export type MyQuestionList = {
  items: Array<{
    id: number;
    subject: string;
    body: string;
    status: string;
    answer: null | string;
    answeredAt: null | string;
    createdAt: string;
  }>;
};

/** GET /me/hotels */
export type MyHotelList = { items: Array<{ id: number; name: string }> };

/** GET /audit-log */
export type AuditLogPage = {
  items: Array<{
    id: number;
    at: string;
    actorId: number;
    actorType: string;
    actor: string;
    action: string;
    entity: string;
    entityId: number;
    companyId: number;
    hotelId: number;
    old: string | null;
    new: { personnelNumber: string };
    reason: string | null;
  }>;
  page: number;
  pageSize: number;
  total: number;
};

/** GET /audit-log/verify */
export type AuditVerifyDto = {
  ok: boolean;
  checkedAt: string;
  chains: Array<{ chainKey: number; rows: number; ok: boolean; brokenAt: string | null; head: string }>;
  unverifiableLegacyRows: string | null;
};

/** GET /schedule/grid */
export type ScheduleGridDto = {
  hotelIds: Array<number>;
  view: string;
  range: string;
  from: string;
  to: string;
  status: string;
  days: Array<{ date: string; holiday: string | null; past: boolean; closedHotelIds: number[] }>;
  rows: Array<{
    key: string;
    kind: string;
    employeeId: number;
    label: string;
    personnelNumber: string;
    isMinor: boolean;
    isFloater: boolean;
    homeHotel: { id: number; name: string };
    isOtherHotel: boolean;
    hotelId: number;
    hotelName: string;
    departmentId: number;
    departmentName: string;
    reduced: boolean;
    targetHours: number;
    creditHours: null | number;
    totalHours: number;
    cells: Array<{
      date: string;
      locked: string | null;
      entries: Array<{
        id: number;
        version: number;
        hotelId: number;
        employeeId: number;
        displayName: string;
        shiftId: number;
        shiftName: null | string;
        departmentId: null | number;
        date: string;
        start: string;
        end: string;
        breakMinutes: number;
        hours: number;
        status: string;
        change: string | null;
        warnings: Array<{
          code: string;
          severity: string;
          message: string;
          details: {
            date?: string;
            from?: number;
            to?: number;
            note?: string;
            gapMinutes?: number;
            side?: string;
            entryId?: number;
          };
        }>;
        isOtherHotel: boolean;
        homeHotel: { id: number; name: string };
        reducedHome: boolean;
        otherHotelName?: string;
        readOnly?: boolean;
      }>;
      absenceIds: Array<number>;
    }>;
  }>;
  absences: Array<{
    id: number;
    employeeId: number;
    displayName: string;
    type: string;
    from: string;
    to: string;
    status: string;
    days: number;
  }>;
  totals: { perDay: Array<{ date: string; hours: number; headcount: number }> };
  changes: unknown[];
  counts: { drafts: number; warnings: number; underStaffed: number; openRequests: number };
  coverage: Array<{
    hotelId: number;
    departmentId: number;
    departmentName: string;
    date: string;
    assigned: number;
    required: number;
    underStaffed: boolean;
  }>;
};

/** GET /announcements */
export type AnnouncementList = {
  items: Array<{
    id: number;
    hotelId: number | null;
    title: string;
    body: string;
    pinned: boolean;
    requiresAck: boolean;
    publishAt: string;
    recipients: number;
    acknowledged: number;
    missing: Array<string>;
  }>;
};

/** GET /live */
export type LiveDto = {
  serverTime: string;
  groups: {
    clockedIn: Array<{
      punchRecordId: number;
      hotelId: number;
      employeeId: number;
      displayName: string;
      departmentName: string;
      since: string;
      plannedEnd: null | string;
      flags: Array<string>;
    }>;
    expectedNotIn: LiveLateDto[];
    noShow: Array<{
      entryId: number;
      hotelId: number;
      employeeId: number;
      displayName: string;
      departmentName: string;
      plannedStart: string;
      plannedEnd: string;
      minutesLate: number;
    }>;
    needsReview: LiveNeedsReviewDto[];
  };
};

/** GET /approvals */
export type ApprovalList = {
  items: Array<{
    id: number;
    type: string;
    hotelId: number;
    employeeId: number;
    displayName: string;
    shiftDate: string;
    plannedStart: string;
    plannedEnd: string;
    actualIn: string;
    actualOut: string;
    paidStart: string;
    paidEnd: string;
    breakMinutes: number;
    requiredBreakMinutes: number;
    paidHours: number;
    flags: Array<string>;
    variations: Array<{ type: string; minutes: number; reason: string; status: string }>;
    status: string;
    notes: string | null;
    ageDays: number;
    overdue: boolean;
  }>;
  total: number;
};

/** GET /approvals */
export type ApprovalAbsenceList = {
  items: Array<{
    id: number;
    type: string;
    hotelId: number;
    employeeId: number;
    displayName: string;
    from: string;
    to: string;
    days: number;
    halfDay: string | null;
    reason: string;
    status: string;
    decisionNote: string | null;
    remaining: number;
    remainingAfter: number;
    conflicts: ViolationDto[];
    understaffing: Array<{ date: string; departmentName: string; assigned: number; required: number }>;
    createdAt: string;
    flags: string[];
  }>;
  total: number;
};

/** GET /approvals */
export type ApprovalCorrectionList = {
  items: Array<{
    id: number;
    type: string;
    hotelId: number;
    employeeId: number;
    displayName: string;
    correctionType: string;
    punchRecordId: number;
    requestedIn: null | string;
    requestedOut: null | string;
    requestedBreakMinutes: null | number;
    reason: string;
    status: string;
    decisionNotes: string | null;
    createdAt: string;
    flags: Array<string>;
  }>;
  total: number;
};

/** GET /settings/rules */
export type RulesSettingsDto = {
  companyId: number;
  hotelId: number | null;
  defaults: {
    dailyMaxMinutes: number;
    dailyWarnMinutes: number;
    restWarnMinutes: number;
    restBlockMinutes: number;
    minorRestMinutes: number;
    minorDailyMaxMinutes: number;
    sundaysFreeMin: number;
    nightWorkerNights: number;
  };
  limits: {
    dailyMaxMinutes: number;
    dailyWarnMinutes: number;
    restWarnMinutes: number;
    restBlockMinutes: number;
    minorRestMinutes: number;
    minorDailyMaxMinutes: number;
    sundaysFreeMin: number;
    nightWorkerNights: number;
  };
  customised: boolean;
  profileName: string | null;
};

/** GET /settings/features */
export type FeatureSettingList = { companyId: number; items: Array<{ feature: string; enabled: boolean }> };

/** GET /compliance/replacement-rest */
export type ReplacementRestList = {
  items: Array<{
    employeeId: number;
    displayName: string;
    date: string;
    kind: string;
    dueBy: string;
    restDayOn: string | null;
    status: string;
  }>;
};

/** GET /compliance/sundays-nights */
export type SundayNightList = {
  year: number;
  items: Array<{
    employeeId: number;
    displayName: string;
    sundaysWorked: number;
    sundaysFree: number;
    sundaysTotal: number;
    nightsLast12Months: number;
  }>;
};

/** GET /me/availability */
export type MyAvailabilityList = {
  items: Array<{
    id: number;
    weekday: number;
    from: string;
    to: string;
    kind: string;
    validFrom: string;
    validTo: null | string;
    note: null | string;
  }>;
};

/** GET /me/documents */
export type MyDocumentList = {
  items: Array<{
    id: number;
    employeeId: number;
    docType: string;
    title: string;
    fileName: string;
    mime: string;
    sizeBytes: number;
    validUntil: string;
    visibleToEmployee: boolean;
    createdAt: string;
  }>;
};

/** GET /me/punch */
export type PunchStatusDto = {
  enabled: boolean;
  hotels: PunchHotelDto[];
  open: {
    hotelId: number;
    source: string;
    since: string;
    onBreak: boolean;
    grossMinutes: number;
    requiredBreakMinutes: number;
    recordedBreakMinutes: number | null;
    suggestedBreakMinutes: number;
    options: Array<number>;
  };
  serverTime: string;
};

/** GET /api-keys */
export type ApiKeyList = {
  items: Array<{
    id: number;
    companyId: number;
    hotelId: number | null;
    name: string;
    prefix: string;
    lastUsedAt: string | null;
    revokedAt: string | null;
    expiresAt: string;
    scopes: Array<string>;
    allowedCidrs: string[];
    lastUsedIp: string | null;
    createdAt: string;
  }>;
};

/** GET /me/vacation */
export type MyVacationDto = { allocated: number; used: number; remaining: number; year: number };

/** GET /me/qualifications */
export type MyQualificationList = {
  items: Array<{ qualificationId: number; name: string; hasExpiry: boolean; validUntil: string }>;
};

/** GET /me/time-off-requests/preview */
export type TimeOffPreviewDto = {
  days: number;
  remaining: number;
  remainingAfter: number;
  sufficient: boolean;
  issues: ViolationDto[];
};

/** GET /me/home */
export type MyHomeDto = {
  today: string;
  nextShifts: Array<{
    id: number;
    date: string;
    start: string;
    end: string;
    breakMinutes: number;
    hotelName: string;
    shiftName: string;
  }>;
  weekHours: number;
  weekPlannedHours: number;
  targetHours: number;
  vacation: { year: number; allocated: number; used: number; remaining: number };
  timeAccount: number;
  clockedIn: boolean;
  notifications: NotificationDto[];
};

/** GET /me/schedule */
export type MyScheduleDto = {
  entries: Array<{
    id: number;
    date: string;
    start: string;
    end: string;
    breakMinutes: number;
    hotelId: number;
    hotelName: string;
    shiftName: string;
    hours: number;
  }>;
  absences: Array<{ id: number; from: string; to: string; type: string; status: string }>;
};

/** GET /me/colleagues */
export type ColleagueList = {
  items: Array<{ employeeId: number; displayName: string; departmentName: string }>;
};

/** GET /me/attendance */
export type AttendanceList = {
  items: Array<{
    decisionNote?: string | null;
    id: number;
    date: string;
    status: string;
    hoursHidden: boolean;
    preliminary?: boolean;
    plannedStart?: string;
    plannedEnd?: string;
    in?: string;
    out?: string | null;
    paidStart?: string;
    paidEnd?: string | null;
    breakMinutes?: number | null;
    paidHours?: number | null;
  }>;
  approvedHours: number;
};

/** GET /me/shifts */
export type MyShiftList = {
  items: Array<{ id: number; name: string; startTime: string; endTime: string; hotelName: string }>;
};

/** GET /me/vacation-notices */
export type MyVacationNoticeList = {
  items: Array<{
    id: number;
    year: number;
    kind: string;
    remainingDays: number;
    sentAt: string;
    acknowledgedAt: string | null;
  }>;
};

/** GET /approvals/swaps */
export type SwapApprovalList = {
  items: Array<{
    id: number;
    hotelId: number;
    scheduleId: number;
    requesterEmployeeId: number;
    counterpartEmployeeId: number;
    counterpartScheduleId: number | null;
    status: string;
    reason: string;
    decisionNote: string | null;
    expiresAt: string;
    createdAt: string;
    requester: string;
    counterpart: string;
    slot: { id: number; date: string; start: string; end: string; shiftName: string; employeeId: number };
    counterpartSlot: SlotDto | null;
    violations: Array<{
      code: string;
      severity: string;
      message: string;
      details: { workMinutes?: number; gapMinutes?: number; side?: string; entryId?: number };
    }>;
  }>;
};

/** GET /questions */
export type QuestionList = {
  items: Array<{
    id: number;
    subject: string;
    body: string;
    status: string;
    answer: string | null;
    answeredAt: string | null;
    createdAt: string;
    employeeId: number;
    displayName: string;
    hotelId: number;
  }>;
};

/** GET /hotels/1/settings */
export type HotelSettingsFull = {
  hotelId: number;
  employeeHoursVisibility: string;
  breakMode: string;
  kioskIdentification: string;
  allowWebPunch: boolean;
  webPunchAllowedCidrs: string[];
};
